# Generated by Django 4.1.7 on 2024-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surnatural_app', '0010_commentaires_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pub_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='pub_videos')),
            ],
        ),
    ]
